import React, { useState } from 'react';
import { Alert } from 'react-native';
import { Redirect, router } from 'expo-router';
import { useAuth } from '../providers/AuthProvider';
import { password as passwordSchema, homeFor } from '../contracts';
import { Screen, Card, Copy, Field, Button, ErrorMessage } from '../components/ui';
export default function Account() {
  const { user, loading, client } = useAuth(); const [channel, setChannel] = useState('EMAIL'); const [code, setCode] = useState(''); const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  if (loading) return <Screen title="Loading…" />; if (homeFor(user) !== '/dashboard') return <Redirect href={homeFor(user)} />;
  async function run(action, success = '') { setBusy(true); setError(''); setMessage(''); try { await action(); setMessage(success); } catch (e) { setError(e.issues?.[0]?.message || e.message); } finally { setBusy(false); } }
  function logout(all) { const action = () => run(() => client.logout(all)); if (all) Alert.alert('Sign out everywhere?', 'This signs your account out on every device and browser.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Sign out', style: 'destructive', onPress: action }]); else action(); }
  return <Screen title="Account and security" subtitle={user.email}><ErrorMessage message={error} />{message && <Copy>{message}</Copy>}<Card><Copy>Email: {user.emailVerified ? 'Verified' : 'Not verified'} · Phone: {user.phoneVerified ? 'Verified' : 'Not verified'}</Copy><Button secondary disabled={busy} onPress={() => { setChannel(channel === 'EMAIL' ? 'PHONE' : 'EMAIL'); setCode(''); }}>Verify {channel === 'EMAIL' ? 'phone instead' : 'email instead'}</Button><Button busy={busy} onPress={() => run(async () => { await client.call('/auth/verification/request', { channel }, 'POST'); }, 'Verification code requested. Check your email or phone.')}>Request {channel.toLowerCase()} code</Button><Field label="Verification code" value={code} onChangeText={setCode} keyboardType="number-pad" autoComplete="one-time-code" /><Button disabled={busy || !code} onPress={() => run(async () => { await client.call('/auth/verification/confirm', { channel, code }, 'POST'); await client.updateUser(); setCode(''); }, 'Contact verified.')}>Confirm code</Button></Card><Card><Copy>Change password</Copy><Field label="Current password" value={currentPassword} onChangeText={setCurrentPassword} secureTextEntry /><Field label="New password" value={newPassword} onChangeText={setNewPassword} secureTextEntry /><Button disabled={busy} onPress={() => run(async () => { passwordSchema.parse(newPassword); await client.call('/auth/change-password', { currentPassword, newPassword }, 'PUT'); await client.clear(); })}>Change password and sign out</Button></Card><Button secondary disabled={busy} onPress={() => logout(false)}>Sign out</Button><Button secondary disabled={busy} onPress={() => logout(true)}>Sign out from all devices</Button><Button secondary disabled={busy} onPress={() => router.replace('/dashboard')}>Back to dashboard</Button></Screen>;
}
