import React, { useEffect, useMemo, useState } from "react";
import api from "../api";
import AdminLayout from "../components/AdminLayout";
import { HandoverDetails } from "../components/HandoverRecord";
import { ProcessingTimeline } from "../components/ProcessingWorkflow";
import { DeliveryProofDetails } from "../components/DeliveryProof";

const statuses = ["OPEN", "INVESTIGATING", "AWAITING_CUSTOMER", "RESOLVED", "CLOSED"];
const priorities = ["LOW", "MEDIUM", "HIGH", "URGENT"];
const categories = ["MISSING_GARMENT", "DAMAGED_GARMENT", "STAIN_REMAINING", "DELAYED_DELIVERY", "BILLING", "OTHER"];
export default function AdminIssues() {
  const [issues, setIssues] = useState([]); const [owners, setOwners] = useState([]); const [loading, setLoading] = useState(true);
  const [filters, setFilters] = useState({ status: "", priority: "", category: "", overdue: false, search: "" });
  const [openId, setOpenId] = useState(null); const [drafts, setDrafts] = useState({}); const [replies, setReplies] = useState({}); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function load() { try { const params = Object.fromEntries(Object.entries(filters).filter(([key, value]) => key !== "search" && value)); const [issueResponse, ownerResponse] = await Promise.all([api.get("/issues/admin", { params }), api.get("/issues/admin/owners")]); setIssues(issueResponse.data.issues); setOwners(ownerResponse.data.owners); setError(""); } catch (err) { setError(err.response?.data?.error || "Could not load issues"); } finally { setLoading(false); } }
  useEffect(() => { load(); }, [filters.status, filters.priority, filters.category, filters.overdue]);
  const shown = useMemo(() => { const query = filters.search.toLowerCase().trim(); if (!query) return issues; return issues.filter((issue) => [issue._id, issue.userId?.name, issue.userId?.phone, issue.orderId?._id, issue.description, issue.category].some((value) => String(value || "").toLowerCase().includes(query))); }, [issues, filters.search]);
  function draft(issue) { return drafts[issue._id] || { status: issue.status, priority: issue.priority, assignedTo: issue.assignedTo?._id || "", resolutionDeadline: issue.resolutionDeadline ? new Date(issue.resolutionDeadline).toISOString().slice(0, 16) : "", compensation: { type: issue.compensation?.type || "NONE", amount: issue.compensation?.amount || 0, note: issue.compensation?.note || "" } }; }
  function setDraft(issue, field, value) { const current = draft(issue); setDrafts({ ...drafts, [issue._id]: field.startsWith("compensation.") ? { ...current, compensation: { ...current.compensation, [field.split(".")[1]]: value } } : { ...current, [field]: value } }); }
  async function save(issue) { setSaving(true); setError(""); try { await api.put(`/issues/admin/${issue._id}`, draft(issue)); setDrafts((current) => { const next = { ...current }; delete next[issue._id]; return next; }); await load(); } catch (err) { setError(err.response?.data?.error || "Could not update issue"); } finally { setSaving(false); } }
  async function reply(issue, visibility) { const text = String(replies[issue._id] || "").trim(); if (!text) return; setSaving(true); setError(""); try { await api.post(`/issues/${issue._id}/replies`, { text, visibility }); setReplies({ ...replies, [issue._id]: "" }); await load(); } catch (err) { setError(err.response?.data?.error || "Could not add message"); } finally { setSaving(false); } }
  if (loading) return <AdminLayout title="Issues"><p className="dg-empty">Loading issues…</p></AdminLayout>;
  const overdueCount = issues.filter((issue) => issue.resolutionDeadline && new Date(issue.resolutionDeadline) < new Date() && !["RESOLVED", "CLOSED"].includes(issue.status)).length;
  return <AdminLayout title="Issues & complaints">
    <div className="dg-issue-metrics"><div><span>Shown</span><strong>{shown.length}</strong></div><div><span>Open</span><strong>{issues.filter((issue) => issue.status === "OPEN").length}</strong></div><div><span>Urgent</span><strong>{issues.filter((issue) => issue.priority === "URGENT").length}</strong></div><div className={overdueCount ? "is-overdue" : ""}><span>Overdue</span><strong>{overdueCount}</strong></div></div>
    <div className="dg-toolbar dg-issue-filters"><input value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value })} placeholder="Search issue, order, customer, phone…" /><select value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })}><option value="">All statuses</option>{statuses.map((value) => <option key={value}>{value}</option>)}</select><select value={filters.priority} onChange={(e) => setFilters({ ...filters, priority: e.target.value })}><option value="">All priorities</option>{priorities.map((value) => <option key={value}>{value}</option>)}</select><select value={filters.category} onChange={(e) => setFilters({ ...filters, category: e.target.value })}><option value="">All categories</option>{categories.map((value) => <option key={value}>{value}</option>)}</select><label className="dg-check"><input type="checkbox" checked={filters.overdue} onChange={(e) => setFilters({ ...filters, overdue: e.target.checked })} /> Overdue only</label></div>
    {error && <div className="dg-error">{error}</div>}
    {!shown.length ? <p className="dg-empty">No issues match these filters.</p> : <div className="dg-admin-issues">{shown.map((issue) => { const open = openId === issue._id; const values = draft(issue); const overdue = issue.resolutionDeadline && new Date(issue.resolutionDeadline) < new Date() && !["RESOLVED", "CLOSED"].includes(issue.status); return <article className={`dg-card dg-admin-issue ${overdue ? "has-overdue" : ""}`} key={issue._id}>
      <div className="dg-issue-head"><div><p className="dg-eyebrow">ISSUE #{issue._id.slice(-6).toUpperCase()} · ORDER #{issue.orderId?._id?.slice(-6).toUpperCase()}</p><h2>{issue.category.replaceAll("_", " ")}</h2><p>{issue.userId?.name} · {issue.userId?.phone}</p></div><div><span className={`dg-status issue-${issue.status.toLowerCase()}`}>{issue.status.replaceAll("_", " ")}</span><span className={`dg-priority priority-${issue.priority.toLowerCase()}`}>{issue.priority}</span>{overdue && <span className="dg-status is-overdue">OVERDUE</span>}</div></div>
      <p className="dg-issue-description">{issue.description}</p><div className="dg-issue-summary"><span>Owner: <b>{issue.assignedTo?.name || "Unassigned"}</b></span><span>Opened: <b>{new Date(issue.createdAt).toLocaleString("en-IN")}</b></span><span>Deadline: <b>{issue.resolutionDeadline ? new Date(issue.resolutionDeadline).toLocaleString("en-IN") : "Not set"}</b></span></div>
      <button className="dg-button dg-secondary" onClick={() => setOpenId(open ? null : issue._id)}>{open ? "Close details" : "Open case"}</button>
      {open && <div className="dg-issue-record"><section><h3>Case controls</h3><div className="dg-form-grid"><label>Status<select value={values.status} onChange={(e) => setDraft(issue, "status", e.target.value)}>{statuses.map((value) => <option key={value}>{value}</option>)}</select></label><label>Priority<select value={values.priority} onChange={(e) => setDraft(issue, "priority", e.target.value)}>{priorities.map((value) => <option key={value}>{value}</option>)}</select></label><label>Owner<select value={values.assignedTo} onChange={(e) => setDraft(issue, "assignedTo", e.target.value)}><option value="">Unassigned</option>{owners.map((owner) => <option key={owner._id} value={owner._id}>{owner.name}</option>)}</select></label><label>Resolution deadline<input type="datetime-local" value={values.resolutionDeadline} onChange={(e) => setDraft(issue, "resolutionDeadline", e.target.value)} /></label></div></section>
      <section><h3>Compensation decision</h3><div className="dg-form-grid"><label>Resolution<select value={values.compensation.type} onChange={(e) => setDraft(issue, "compensation.type", e.target.value)}>{["NONE", "REFUND", "CREDIT", "REPROCESS"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Amount<input type="number" min="0" step="0.01" value={values.compensation.amount} onChange={(e) => setDraft(issue, "compensation.amount", Number(e.target.value))} /></label></div><label>Decision note<textarea rows="2" value={values.compensation.note} onChange={(e) => setDraft(issue, "compensation.note", e.target.value)} /></label></section><button className="dg-button" disabled={saving} onClick={() => save(issue)}>{saving ? "Saving…" : "Save case"}</button>
      <section><h3>Conversation & internal notes</h3><div className="dg-issue-thread">{issue.messages.map((message) => <div key={message._id} className={message.visibility === "INTERNAL" ? "is-internal" : message.addedByRole === "CUSTOMER" ? "from-customer" : "from-team"}><b>{message.addedByName} · {message.visibility}</b><p>{message.text}</p><small>{new Date(message.timestamp).toLocaleString("en-IN")}</small></div>)}{!issue.messages.length && <p className="dg-muted text-sm">No messages yet.</p>}</div><div className="dg-reply-box"><textarea rows="2" value={replies[issue._id] || ""} onChange={(e) => setReplies({ ...replies, [issue._id]: e.target.value })} placeholder="Write a customer reply or internal note…" /><div className="flex gap-2"><button className="dg-button" disabled={saving} onClick={() => reply(issue, "CUSTOMER")}>Reply to customer</button><button className="dg-button dg-secondary" disabled={saving} onClick={() => reply(issue, "INTERNAL")}>Add internal note</button></div></div></section>
      {!!issue.photos?.length && <section><h3>Customer photos</h3><div className="dg-photo-row">{issue.photos.map((photo, index) => <a key={index} href={photo.url || photo.dataUrl} target="_blank" rel="noreferrer"><img src={photo.url || photo.dataUrl} alt={`Issue evidence ${index + 1}`} /></a>)}</div></section>}
      <details><summary>Linked order evidence</summary><div className="dg-linked-evidence"><section><h3>Pickup record</h3><HandoverDetails handover={issue.orderId?.handover} /></section>{issue.orderId?.processing?.requiredStages?.length > 0 && <section><h3>Processing & quality</h3><ProcessingTimeline order={issue.orderId} /></section>}<section><h3>Delivery proof</h3><DeliveryProofDetails proof={issue.orderId?.deliveryProof} /></section></div></details>
      <details><summary>Case audit trail</summary><ul className="dg-audit-list">{issue.auditTrail.map((entry, index) => <li key={index}><strong>{entry.action}</strong> · {entry.changedByName} ({entry.changedByRole}) · {new Date(entry.timestamp).toLocaleString("en-IN")}<br />{entry.note}</li>)}</ul></details>
      </div>}
    </article>; })}</div>}
  </AdminLayout>;
}
