import React, { useEffect, useState } from "react";
import api from "../api";
import AdminLayout from "../components/AdminLayout";

const today = new Date().toISOString().slice(0, 10);
export default function AdminOperations() {
  const [data, setData] = useState({ payouts: [], riderScores: [], partnerScores: [], deletionRequests: [], riders: [], partners: [] });
  const [orders, setOrders] = useState([]); const [slots, setSlots] = useState([]); const [manifest, setManifest] = useState([]); const [mapsUrl, setMapsUrl] = useState(""); const [date, setDate] = useState(today); const [error, setError] = useState("");
  const [payout, setPayout] = useState({ payeeType: "RIDER", payeeId: "", periodStart: today, periodEnd: today, commissionType: "FLAT_PER_ORDER", commissionRate: 50 });
  const [schedule, setSchedule] = useState({ orderId: "", slotId: "" });
  async function load() { const [overview, orderResponse, slotResponse] = await Promise.all([api.get("/operations/admin/overview"), api.get("/orders/admin/all"), api.get("/admin/slots")]); setData(overview.data); setOrders(orderResponse.data.orders || []); setSlots((slotResponse.data.slots || []).filter(s => s.type === "DELIVERY")); }
  useEffect(() => { load().catch(err => setError(err.response?.data?.error || "Could not load operations")); }, []);
  async function loadManifest() { try { const response = await api.get("/operations/manifest", { params: { date } }); setManifest(response.data.stops || []); setMapsUrl(response.data.mapsUrl || ""); } catch (err) { setError(err.response?.data?.error || "Could not load manifest"); } }
  async function createPayout(e) { e.preventDefault(); try { await api.post("/operations/admin/payouts", payout); await load(); } catch (err) { setError(err.response?.data?.error || "Could not create payout"); } }
  async function updatePayout(id, status) { const paymentReference = status === "PAID" ? window.prompt("Payment reference") || "" : ""; try { await api.put(`/operations/admin/payouts/${id}`, { status, paymentReference }); await load(); } catch (err) { setError(err.response?.data?.error || "Could not update payout"); } }
  async function assignDelivery(e) { e.preventDefault(); try { await api.put(`/operations/admin/orders/${schedule.orderId}/delivery-slot`, { slotId: schedule.slotId }); await load(); } catch (err) { setError(err.response?.data?.error || "Could not schedule delivery"); } }
  async function reviewDeletion(id, status) { const reviewNote = window.prompt("Review note (optional)") || ""; try { await api.put(`/operations/admin/deletion-requests/${id}`, { status, reviewNote }); await load(); } catch (err) { setError(err.response?.data?.error || "Could not update request"); } }
  const payees = payout.payeeType === "RIDER" ? data.riders : data.partners;
  return <AdminLayout title="Operations control"><div className="dg-operations-grid">
    {error && <p className="dg-error">{error}</p>}
    <section className="dg-card"><p className="dg-eyebrow">DELIVERY PLANNING</p><h2>Schedule a delivery</h2><form className="dg-form-grid mt-4" onSubmit={assignDelivery}><label>Order<select required value={schedule.orderId} onChange={e => setSchedule({ ...schedule, orderId: e.target.value })}><option value="">Choose order</option>{orders.filter(o => !["DELIVERED", "CANCELLED"].includes(o.status)).map(o => <option key={o._id} value={o._id}>#{o._id.slice(-6).toUpperCase()} · {o.userId?.name}</option>)}</select></label><label>Delivery slot<select required value={schedule.slotId} onChange={e => setSchedule({ ...schedule, slotId: e.target.value })}><option value="">Choose slot</option>{slots.map(s => <option key={s._id} value={s._id}>{new Date(s.date).toLocaleDateString("en-IN")} · {s.timeRange} ({s.bookedCount}/{s.maxOrders})</option>)}</select></label><button className="dg-button">Assign delivery slot</button></form></section>
    <section className="dg-card"><p className="dg-eyebrow">DAILY ROUTES</p><h2>Rider manifest</h2><div className="dg-inline-form mt-4"><input type="date" value={date} onChange={e => setDate(e.target.value)} /><button className="dg-button dg-secondary" onClick={loadManifest}>Build manifest</button>{mapsUrl && <a className="dg-button" href={mapsUrl} target="_blank" rel="noreferrer">Open planned route</a>}</div>{manifest.map(stop => <article className="dg-operation-row" key={stop.order._id}><strong>{stop.sequence}. #{stop.order._id.slice(-6).toUpperCase()}</strong><span>{stop.order.userId?.name} · {stop.order.address?.line1}, {stop.order.address?.pincode}</span><span>{stop.order.pickupSlot?.timeRange || stop.order.deliverySlot?.timeRange || "Unscheduled"} · {stop.order.riderId?.name || "Unassigned"}</span></article>)}</section>
    <section className="dg-card"><p className="dg-eyebrow">COMMISSIONS</p><h2>Create payout record</h2><form className="dg-form-grid mt-4" onSubmit={createPayout}><label>Payee type<select value={payout.payeeType} onChange={e => setPayout({ ...payout, payeeType: e.target.value, payeeId: "" })}><option value="RIDER">Rider</option><option value="PARTNER">Laundry partner</option></select></label><label>Payee<select required value={payout.payeeId} onChange={e => setPayout({ ...payout, payeeId: e.target.value })}><option value="">Choose payee</option>{payees.map(p => <option key={p._id} value={p._id}>{p.name || p.businessName}</option>)}</select></label><label>From<input type="date" required value={payout.periodStart} onChange={e => setPayout({ ...payout, periodStart: e.target.value })} /></label><label>To<input type="date" required value={payout.periodEnd} onChange={e => setPayout({ ...payout, periodEnd: e.target.value })} /></label><label>Commission<select value={payout.commissionType} onChange={e => setPayout({ ...payout, commissionType: e.target.value })}><option value="FLAT_PER_ORDER">Flat per order</option><option value="PERCENT">Percent of order value</option></select></label><label>Rate<input type="number" min="0" step="0.01" value={payout.commissionRate} onChange={e => setPayout({ ...payout, commissionRate: e.target.value })} /></label><button className="dg-button">Create draft payout</button></form><div className="dg-table-scroll mt-5"><table><thead><tr><th>Payee</th><th>Period</th><th>Orders</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.payouts.map(row => <tr key={row._id}><td>{row.riderId?.name || row.partnerId?.businessName}</td><td>{new Date(row.periodStart).toLocaleDateString("en-IN")} – {new Date(row.periodEnd).toLocaleDateString("en-IN")}</td><td>{row.orderIds?.length || 0}</td><td>₹{row.amount}</td><td>{row.status}</td><td>{row.status === "DRAFT" ? <button className="dg-back" onClick={() => updatePayout(row._id, "APPROVED")}>Approve</button> : row.status === "APPROVED" ? <button className="dg-back" onClick={() => updatePayout(row._id, "PAID")}>Mark paid</button> : row.paymentReference || "Paid"}</td></tr>)}</tbody></table></div></section>
    <section className="dg-card"><p className="dg-eyebrow">QUALITY</p><h2>Customer ratings</h2><div className="dg-score-grid"><div><h3>Riders</h3>{data.riderScores.map(row => <p key={row.name}><strong>{row.score}/5</strong> · {row.name} ({row.ratings})</p>)}</div><div><h3>Partners</h3>{data.partnerScores.map(row => <p key={row.name}><strong>{row.score}/5</strong> · {row.name} ({row.ratings})</p>)}</div></div></section>
    <section className="dg-card"><p className="dg-eyebrow">PRIVACY</p><h2>Customer deletion requests</h2>{data.deletionRequests.length === 0 ? <p className="dg-muted">No requests.</p> : data.deletionRequests.map(row => <article className="dg-operation-row" key={row._id}><strong>{row.userId?.name || "Deleted customer"}</strong><span>{row.userId?.email} · {row.status}</span>{row.status === "PENDING" && <span><button className="dg-back" onClick={() => reviewDeletion(row._id, "REJECTED")}>Reject</button> <button className="dg-back" onClick={() => reviewDeletion(row._id, "COMPLETED")}>Approve & anonymise</button></span>}</article>)}</section>
  </div></AdminLayout>;
}
