import React, { useEffect, useMemo, useState } from "react";
import api from "../api";
import AdminLayout from "../components/AdminLayout";

const today = () => new Date().toISOString().slice(0, 10);
const daysAgo = (days) => { const date = new Date(); date.setDate(date.getDate() - days); return date.toISOString().slice(0, 10); };
const money = (value) => `₹${Number(value || 0).toLocaleString("en-IN", { maximumFractionDigits: 2 })}`;
const valueOrDash = (value, suffix = "") => value === null || value === undefined ? "—" : `${value}${suffix}`;

export default function AdminReports() {
  const [filters, setFilters] = useState({ from: daysAgo(29), to: today(), status: "", service: "", riderId: "", partnerId: "" });
  const [options, setOptions] = useState({ riders: [], partners: [], services: [] });
  const [report, setReport] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load(activeFilters = filters) { setLoading(true); setError(""); try { const response = await api.get("/admin/reports", { params: Object.fromEntries(Object.entries(activeFilters).filter(([, value]) => value !== "")) }); setReport(response.data.report); } catch (err) { setError(err.response?.data?.error || "Could not load reports"); } finally { setLoading(false); } }
  useEffect(() => { Promise.all([api.get("/admin/report-options"), api.get("/admin/reports", { params: { from: filters.from, to: filters.to } })]).then(([optionResponse, reportResponse]) => { setOptions(optionResponse.data); setReport(reportResponse.data.report); }).catch((err) => setError(err.response?.data?.error || "Could not load reports")).finally(() => setLoading(false)); }, []);
  function preset(days) { const next = { ...filters, from: daysAgo(days - 1), to: today() }; setFilters(next); load(next); }
  const maxTrend = useMemo(() => Math.max(1, ...(report?.trends || []).map((row) => row.revenue)), [report]);
  function exportCsv() {
    if (!report) return;
    const rows = [["DHOBI GHAT BUSINESS REPORT"], ["From", filters.from, "To", filters.to], [], ["SUMMARY"], ["Orders", report.totals.orders], ["Garments", report.totals.garments], ["Gross revenue", report.totals.revenue], ["Refunds", report.totals.refunds], ["Net revenue", report.totals.netRevenue], ["Average order value", report.totals.averageOrderValue], ["Cancellation rate", `${report.totals.cancellationRate}%`], ["Unique customers", report.customers.unique], ["New customers", report.customers.new], ["Repeat customers", report.customers.repeat], [], ["DAILY TREND"], ["Date", "Orders", "Garments", "Revenue"], ...report.trends.map((row) => [row.date, row.orders, row.garments, row.revenue]), [], ["SERVICES"], ["Service", "Orders", "Garments", "Revenue"], ...report.services.map((row) => [row.name, row.orders, row.garments, row.revenue]), [], ["GARMENTS"], ["Garment", "Quantity", "Revenue"], ...report.garments.map((row) => [row.name, row.quantity, row.revenue]), [], ["RIDERS"], ["Rider", "Assigned", "Pickups", "Delivered", "Completion %", "Average delivery hours", "Complaints"], ...report.riders.map((row) => [row.name, row.assigned, row.pickups, row.delivered, row.completionRate, row.averageDeliveryHours ?? "", row.complaints]), [], ["LAUNDRY PARTNERS"], ["Partner", "Orders", "Completed", "Completion %", "Average processing hours", "Delayed", "Quality failures"], ...report.partners.map((row) => [row.name, row.orders, row.completed, row.completionRate, row.averageProcessingHours ?? "", row.delayed, row.qualityFailures]), [], ["PICKUP SLOTS"], ["Date", "Time", "Capacity", "Booked", "Utilization %"], ...report.slots.rows.map((row) => [new Date(row.date).toLocaleDateString("en-IN"), row.timeRange, row.capacity, row.booked, row.utilization])];
    const csv = rows.map((row) => row.map((cell) => `"${String(cell ?? "").replaceAll('"', '""')}"`).join(",")).join("\n");
    const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); link.download = `dhobi-ghat-report-${filters.from}-to-${filters.to}.csv`; link.click(); URL.revokeObjectURL(link.href);
  }
  return <AdminLayout title="Reports & analytics">
    <div className="dg-report-presets"><button onClick={() => preset(7)}>Last 7 days</button><button onClick={() => preset(30)}>Last 30 days</button><button onClick={() => preset(90)}>Last 90 days</button></div>
    <form className="dg-report-filters" onSubmit={(event) => { event.preventDefault(); load(); }}><label>From<input type="date" required value={filters.from} onChange={(e) => setFilters({ ...filters, from: e.target.value })} /></label><label>To<input type="date" required value={filters.to} onChange={(e) => setFilters({ ...filters, to: e.target.value })} /></label><label>Status<select value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })}><option value="">All statuses</option>{["ORDER_PLACED", "PICKUP_ASSIGNED", "RIDER_ON_THE_WAY", "PICKED_UP", "PROCESSING", "READY", "OUT_FOR_DELIVERY", "DELIVERED", "CANCELLED"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Service<select value={filters.service} onChange={(e) => setFilters({ ...filters, service: e.target.value })}><option value="">All services</option>{options.services.map((service) => <option key={service._id} value={service.code}>{service.name}</option>)}</select></label><label>Rider<select value={filters.riderId} onChange={(e) => setFilters({ ...filters, riderId: e.target.value })}><option value="">All riders</option>{options.riders.map((rider) => <option key={rider._id} value={rider._id}>{rider.name}</option>)}</select></label><label>Partner<select value={filters.partnerId} onChange={(e) => setFilters({ ...filters, partnerId: e.target.value })}><option value="">All partners</option>{options.partners.map((partner) => <option key={partner._id} value={partner._id}>{partner.businessName}</option>)}</select></label><button className="dg-button" disabled={loading}>{loading ? "Loading…" : "Apply filters"}</button><button type="button" className="dg-button dg-secondary" disabled={!report} onClick={exportCsv}>Export CSV</button></form>
    {error && <div className="dg-error">{error}</div>}
    {loading && !report ? <p className="dg-empty">Building your report…</p> : report && <div className="dg-report">
      <section className="dg-report-kpis"><ReportCard label="Net revenue" value={money(report.totals.netRevenue)} detail={`${money(report.totals.refunds)} refunded`} /><ReportCard label="Orders" value={report.totals.orders} detail={`${report.totals.deliveredOrders} delivered`} /><ReportCard label="Average order" value={money(report.totals.averageOrderValue)} detail={`${report.totals.garments} garments`} /><ReportCard label="Customers" value={report.customers.unique} detail={`${report.customers.repeat} repeat`} /><ReportCard label="Cancellation rate" value={`${report.totals.cancellationRate}%`} detail={`${report.totals.cancelledOrders} cancelled`} /><ReportCard label="Slot utilization" value={`${report.slots.utilization}%`} detail={`${report.slots.booked}/${report.slots.capacity} booked`} /></section>
      <section className="dg-card dg-report-panel"><div className="dg-report-title"><div><p className="dg-eyebrow">REVENUE TREND</p><h2>Daily business</h2></div><strong>{money(report.totals.revenue)} gross</strong></div><div className="dg-trend-chart" role="img" aria-label="Daily revenue chart">{report.trends.map((row) => <div className="dg-trend-column" key={row.date} title={`${row.date}: ${money(row.revenue)}, ${row.orders} orders`}><span>{row.revenue ? money(row.revenue) : ""}</span><div style={{ height: `${Math.max(row.revenue ? 8 : 2, row.revenue / maxTrend * 150)}px` }} /><small>{new Date(`${row.date}T00:00:00`).toLocaleDateString("en-IN", { day: "numeric", month: "short" })}</small></div>)}</div></section>
      <section className="dg-report-insights"><ReportInsight title="Customers" rows={[["New customers", report.customers.new], ["Repeat customers", report.customers.repeat], ["Unique customers", report.customers.unique]]} /><ReportInsight title="Complaints" rows={[["Open", report.issues.open], ["Overdue", report.issues.overdue], ["Resolved", report.issues.resolved], ["Total", report.issues.total]]} /><ReportInsight title="Quality" rows={[["Quality failures", report.quality.qualityFailures], ["Processing issues", report.quality.processingIssues], ["Intake differences", report.quality.intakeDiscrepancies], ["Claims / 100 deliveries", report.quality.claimsPer100Deliveries]]} /></section>
      <ReportTable title="Services" headers={["Service", "Orders", "Garments", "Revenue"]} rows={report.services.map((row) => [row.name, row.orders, row.garments, money(row.revenue)])} empty="No service activity in this period." />
      <ReportTable title="Most-used garments" headers={["Garment", "Quantity", "Revenue"]} rows={report.garments.slice(0, 15).map((row) => [row.name, row.quantity, money(row.revenue)])} empty="No garment activity in this period." />
      <ReportTable title="Rider performance" headers={["Rider", "Assigned", "Pickups", "Delivered", "Completion", "Avg delivery", "Complaints"]} rows={report.riders.map((row) => [row.name, row.assigned, row.pickups, row.delivered, `${row.completionRate}%`, valueOrDash(row.averageDeliveryHours, "h"), row.complaints])} empty="No rider assignments in this period." />
      <ReportTable title="Laundry partner performance" headers={["Partner", "Orders", "Completed", "Completion", "Avg processing", "Delayed", "Quality failures"]} rows={report.partners.map((row) => [row.name, row.orders, row.completed, `${row.completionRate}%`, valueOrDash(row.averageProcessingHours, "h"), row.delayed, row.qualityFailures])} empty="No partner assignments in this period." />
      <ReportTable title="Complaint categories" headers={["Category", "Cases"]} rows={report.issues.categories.map((row) => [row.category.replaceAll("_", " "), row.count])} empty="No complaints linked to these orders." />
      <ReportTable title="Pickup-slot capacity" headers={["Date", "Window", "Capacity", "Booked", "Utilization"]} rows={report.slots.rows.map((row) => [new Date(row.date).toLocaleDateString("en-IN"), row.timeRange, row.capacity, row.booked, `${row.utilization}%`])} empty="No pickup slots in this period." />
    </div>}
  </AdminLayout>;
}

function ReportCard({ label, value, detail }) { return <div className="dg-report-card"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>; }
function ReportInsight({ title, rows }) { return <div className="dg-card dg-report-insight"><h3>{title}</h3>{rows.map(([label, value]) => <p key={label}><span>{label}</span><strong>{value}</strong></p>)}</div>; }
function ReportTable({ title, headers, rows, empty }) { return <section className="dg-card dg-report-panel"><div className="dg-report-title"><h2>{title}</h2><span>{rows.length} rows</span></div>{!rows.length ? <p className="dg-empty">{empty}</p> : <><p className="dg-table-hint">Swipe sideways to view all columns.</p><div className="dg-table-scroll" tabIndex="0" role="region" aria-label={`${title} table`}><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row, rowIndex) => <tr key={rowIndex}>{row.map((cell, index) => <td key={index}>{cell}</td>)}</tr>)}</tbody></table></div></>}</section>; }
