import React from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors as c } from '../theme';
export function Screen({ title, subtitle, children }) { return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={s.safe} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.page}><View style={s.brand}><Text style={s.mark}>DG</Text><View><Text style={s.brandName}>Dhobi Ghat</Text><Text style={s.eyebrow}>APNA LAUNDRY</Text></View></View><Text style={s.title}>{title}</Text>{subtitle && <Text style={s.muted}>{subtitle}</Text>}{children}</ScrollView></KeyboardAvoidingView></SafeAreaView>; }
export function Card({ children }) { return <View style={s.card}>{children}</View>; }
export function Button({ children, onPress, busy, disabled, secondary }) { return <Pressable accessibilityRole="button" disabled={busy || disabled} onPress={onPress} style={[s.button, secondary && s.secondary, (busy || disabled) && { opacity: .5 }]}>{busy ? <ActivityIndicator color={secondary ? c.navy : c.paper} /> : <Text style={[s.buttonText, secondary && { color: c.navy }]}>{children}</Text>}</Pressable>; }
export function Field({ label, ...props }) { return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} placeholderTextColor={c.muted} autoCapitalize="none" style={s.input} {...props} /></View>; }
export function ErrorMessage({ message }) { return message ? <Text accessibilityRole="alert" style={s.error}>{message}</Text> : null; }
export function Copy({ children }) { return <Text style={s.muted}>{children}</Text>; }
export const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: c.cream }, page: { padding: 24, gap: 18, flexGrow: 1, maxWidth: 600, width: '100%', alignSelf: 'center' }, brand: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 22 }, mark: { backgroundColor: c.navy, color: c.gold, padding: 14, borderRadius: 14, fontWeight: '700', fontSize: 20 }, brandName: { color: c.navy, fontSize: 27, fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif' }, eyebrow: { color: c.muted, fontSize: 8, letterSpacing: 1 }, title: { fontSize: 34, color: c.navy, fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif' }, muted: { color: c.muted, fontSize: 15, lineHeight: 23 }, card: { padding: 20, gap: 16, borderRadius: 20, backgroundColor: c.paper, borderWidth: 1, borderColor: c.line }, field: { gap: 8 }, label: { color: c.ink, fontWeight: '600', fontSize: 14 }, input: { backgroundColor: c.paper, borderColor: '#c9cece', borderWidth: 1, borderRadius: 12, minHeight: 50, padding: 13, color: c.ink, fontSize: 16 }, button: { backgroundColor: c.navy, borderRadius: 12, padding: 15, minHeight: 50, alignItems: 'center', justifyContent: 'center' }, secondary: { backgroundColor: c.paper, borderWidth: 1, borderColor: c.line }, buttonText: { color: c.paper, fontWeight: '600', fontSize: 15 }, error: { color: c.error, backgroundColor: '#fff0ed', padding: 12, borderRadius: 10, lineHeight: 21 } });
